// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class UIConstantFiles.
// Make any needed changes in class UIConstantFiles.

namespace PerformanceMonitor
{
    public class UIEventName
    {
        // Events group name.
        public const string GroupName = "PerformanceMonitor";

        // Events from UI to C#.
        public const string MainButtonClicked = "mainButtonClicked";
        public const string MainPanelMoved = "mainPanelMoved";

        // Events from C# to UI for main panel.
        public const string MainPanelVisible = "mainPanelVisible";
        public const string MainPanelPositionX = "mainPanelPositionX";
        public const string MainPanelPositionY = "mainPanelPositionY";

        // Events from C# to UI for data values.
        public const string CurrentGameMinute = "currentGameMinute";
        public const string PreviousGameMinute = "previousGameMinute";
        public const string FrameRate = "frameRate";
        public const string GPUUsage = "gpuUsage";
        public const string CPUUsage = "cpuUsage";
        public const string MemoryUsage = "memoryUsage";

        // Events from C# to UI for whether or not to show data values.
        public const string ShowGPUUsage = "showGPUUsage";
        public const string ShowCPUUsage = "showCPUUsage";
        public const string ShowMemoryUsage = "showMemoryUsage";
    }

    public class UITranslationKey
    {
        // Mod title and description.
        public const string Title = "PerformanceMonitor.Title";
        public const string Description = "PerformanceMonitor.Description";

        // Settings.
        public const string SettingTitle = "Options.SECTION[PerformanceMonitor.PerformanceMonitor.Mod]";
        public const string SettingBindingMap = "Options.INPUT_MAP[PerformanceMonitor.PerformanceMonitor.Mod]";
        public const string SettingGroupGeneral = "Options.GROUP[PerformanceMonitor.PerformanceMonitor.Mod.General]";
        public const string SettingActivationKeyBinding = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod/ActivationKeyBinding/binding]";
        public const string SettingActivationKeyBindingLabel = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ActivationKeyBinding]";
        public const string SettingActivationKeyBindingDesc = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ActivationKeyBinding]";
        public const string SettingResetWindowPositionLabel = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ResetMainPanelPosition]";
        public const string SettingResetWindowPositionDesc = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ResetMainPanelPosition]";
        public const string SettingGroupAbout = "Options.GROUP[PerformanceMonitor.PerformanceMonitor.Mod.About]";
        public const string SettingModVersionLabel = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ModVersion]";

        // Measurement row labels.
        public const string RowLabelCurrentGameMinute = "PerformanceMonitor.RowLabelCurrentGameMinute";
        public const string RowLabelPreviousGameMinute = "PerformanceMonitor.RowLabelPreviousGameMinute";
        public const string RowLabelFrameRate = "PerformanceMonitor.RowLabelFrameRate";
        public const string RowLabelGPUUsage = "PerformanceMonitor.RowLabelGPUUsage";
        public const string RowLabelCPUUsage = "PerformanceMonitor.RowLabelCPUUsage";
        public const string RowLabelMemoryUsage = "PerformanceMonitor.RowLabelMemoryUsage";

        // Measurement tool tips.
        public const string ToolTipCurrentGameMinute = "PerformanceMonitor.ToolTipCurrentGameMinute";
        public const string ToolTipPreviousGameMinute = "PerformanceMonitor.ToolTipPreviousGameMinute";
        public const string ToolTipFrameRate = "PerformanceMonitor.ToolTipFrameRate";
        public const string ToolTipGPUUsage = "PerformanceMonitor.ToolTipGPUUsage";
        public const string ToolTipCPUUsage = "PerformanceMonitor.ToolTipCPUUsage";
        public const string ToolTipMemoryUsage = "PerformanceMonitor.ToolTipMemoryUsage";
    }

    public class ModSettingsDefaults
    {
        // Defaults for mod settings.
        public const bool MainPanelVisible = false;
        public const int MainPanelPositionX = 175;
        public const int MainPanelPositionY = 55;
    }
}
