// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class UIConstantFiles.
// Make any needed changes in class UIConstantFiles.

export class UIEventName
{
    // Events group name.
    public static GroupName: string = "PerformanceMonitor";

    // Events from UI to C#.
    public static MainButtonClicked: string = "mainButtonClicked";
    public static MainPanelMoved: string = "mainPanelMoved";

    // Events from C# to UI for main panel.
    public static MainPanelVisible: string = "mainPanelVisible";
    public static MainPanelPositionX: string = "mainPanelPositionX";
    public static MainPanelPositionY: string = "mainPanelPositionY";

    // Events from C# to UI for data values.
    public static CurrentGameMinute: string = "currentGameMinute";
    public static PreviousGameMinute: string = "previousGameMinute";
    public static FrameRate: string = "frameRate";
    public static GPUUsage: string = "gpuUsage";
    public static CPUUsage: string = "cpuUsage";
    public static MemoryUsage: string = "memoryUsage";

    // Events from C# to UI for whether or not to show data values.
    public static ShowGPUUsage: string = "showGPUUsage";
    public static ShowCPUUsage: string = "showCPUUsage";
    public static ShowMemoryUsage: string = "showMemoryUsage";
}

export class UITranslationKey
{
    // Mod title and description.
    public static Title: string = "PerformanceMonitor.Title";
    public static Description: string = "PerformanceMonitor.Description";

    // Settings.
    public static SettingTitle: string = "Options.SECTION[PerformanceMonitor.PerformanceMonitor.Mod]";
    public static SettingBindingMap: string = "Options.INPUT_MAP[PerformanceMonitor.PerformanceMonitor.Mod]";
    public static SettingGroupGeneral: string = "Options.GROUP[PerformanceMonitor.PerformanceMonitor.Mod.General]";
    public static SettingActivationKeyBinding: string = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod/ActivationKeyBinding/binding]";
    public static SettingActivationKeyBindingLabel: string = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ActivationKeyBinding]";
    public static SettingActivationKeyBindingDesc: string = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ActivationKeyBinding]";
    public static SettingResetWindowPositionLabel: string = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ResetMainPanelPosition]";
    public static SettingResetWindowPositionDesc: string = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ResetMainPanelPosition]";
    public static SettingGroupAbout: string = "Options.GROUP[PerformanceMonitor.PerformanceMonitor.Mod.About]";
    public static SettingModVersionLabel: string = "Options.OPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ModVersion]";
    public static SettingModVersionDesc: string = "Options.OPTION_DESCRIPTION[PerformanceMonitor.PerformanceMonitor.Mod.ModSettings.ModVersion]";

    // Measurement row labels.
    public static RowLabelCurrentGameMinute: string = "PerformanceMonitor.RowLabelCurrentGameMinute";
    public static RowLabelPreviousGameMinute: string = "PerformanceMonitor.RowLabelPreviousGameMinute";
    public static RowLabelFrameRate: string = "PerformanceMonitor.RowLabelFrameRate";
    public static RowLabelGPUUsage: string = "PerformanceMonitor.RowLabelGPUUsage";
    public static RowLabelCPUUsage: string = "PerformanceMonitor.RowLabelCPUUsage";
    public static RowLabelMemoryUsage: string = "PerformanceMonitor.RowLabelMemoryUsage";

    // Measurement tool tips.
    public static ToolTipCurrentGameMinute: string = "PerformanceMonitor.ToolTipCurrentGameMinute";
    public static ToolTipPreviousGameMinute: string = "PerformanceMonitor.ToolTipPreviousGameMinute";
    public static ToolTipFrameRate: string = "PerformanceMonitor.ToolTipFrameRate";
    public static ToolTipGPUUsage: string = "PerformanceMonitor.ToolTipGPUUsage";
    public static ToolTipCPUUsage: string = "PerformanceMonitor.ToolTipCPUUsage";
    public static ToolTipMemoryUsage: string = "PerformanceMonitor.ToolTipMemoryUsage";
}

export class ModSettingsDefaults
{
    // Defaults for mod settings.
    public static MainPanelVisible: boolean = false;
    public static MainPanelPositionX: number = 175;
    public static MainPanelPositionY: number = 55;
}
